### PR TITLE
Direct Payment Implementation

### PR DESCRIPTION
**Pull request by kskunca314**

### CODE REVIEW

**Comment by jasmind-monri** [comment]
@kskunca314 The webView closes before I complete the payment on PayCek and the transaction goes into pending. Can you check that out please?

**Comment by kskunca314** [comment]
> @kskunca314 The webView closes before I complete the payment on PayCek and the transaction goes into pending. Can you check that out please?

Improvement has been implemented, please check again.

**Review by jasmind-monri — APPROVED** [review]
LGTM

**Review by jasminsuljic — APPROVED** [review]
LGTM

**Pull request merged**
